language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aossipov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aossipov/docker-react npm run test